# .github/workflows/detect-changes.yml
# A workflow file that detect changes and trigger another workflow in another repository.
# Here that repository is yashksaini-coder/Update-Leetcode-Gist which is used to update a pinned leetcode github gist.
# Disable this repo if you don't have any pinned leetcode github gist.

name: Detect Changes and Trigger Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to the branch you want to monitor
  pull_request:
    branches:
      - main  # Trigger on pull request to the branch

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Trigger workflow in another repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Changes detected. Workflow Triggered!"
        curl -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GITHUB_TOKEN" \
        https://api.github.com/repos/yashksaini-coder/Update-Leetcode-Gist/actions/workflows/main.yml/dispatches \
        -d '{"ref":"main"}'
